---
  extends: airbnb-base
  env:
    amd: true
    browser: true
    es6: true
    jquery: true
    node: true
    webextensions: true
  parserOptions:
    sourceType: module
    ecmaVersion: 2017
  rules:
    generator-star-spacing:
      - 2
      - before: true
        after: true
    no-shadow: 0
    require-yield: 0
    no-param-reassign: 0
    comma-dangle:
      - error
      - never
    no-underscore-dangle: 0
    import/no-extraneous-dependencies:
      - 2
      - devDependencies: true
    import/order:
      - error
    func-names: 0
    no-unused-expressions: 0
    no-restricted-syntax: 0
    no-await-in-loop: 0
    no-console: 0
    prefer-arrow-callback: 1
    no-use-before-define:
      - 2
      - functions: false
    space-before-function-paren:
      - 2
      - always
    max-len:
      - 2
      - 120
      - 2
      -
        ignoreStrings: true
        ignoreComments: true
        ignoreTemplateLiterals: true
    semi:
      - 2
      - never
    strict:
      - 2
      - global
    arrow-parens:
      - 2
      - always
